/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class passvecjni */

#ifndef _Included_passvecjni
#define _Included_passvecjni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     passvecjni
 * Method:    passvec
 * Signature: (Ljava/util/ArrayList;I)V
 */
JNIEXPORT void JNICALL Java_passvecjni_passvec
  (JNIEnv *, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
