/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_ignite_examples_datagrid_CachePutGetComplexExample */

#ifndef _Included_org_apache_ignite_examples_datagrid_CachePutGetComplexExample
#define _Included_org_apache_ignite_examples_datagrid_CachePutGetComplexExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_ignite_examples_datagrid_CachePutGetComplexExample
 * Method:    cppget
 * Signature: (Lorg/apache/ignite/IgniteCache;Ljava/lang/Integer;)Lorg/apache/ignite/examples/datagrid/Person;
 */
JNIEXPORT jobject JNICALL Java_org_apache_ignite_examples_datagrid_CachePutGetComplexExample_cppget
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_apache_ignite_examples_datagrid_CachePutGetComplexExample
 * Method:    avg
 * Signature: (Lorg/apache/ignite/IgniteCache;)D
 */
JNIEXPORT jdouble JNICALL Java_org_apache_ignite_examples_datagrid_CachePutGetComplexExample_avg
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_apache_ignite_examples_datagrid_CachePutGetComplexExample
 * Method:    zipcount
 * Signature: (Lorg/apache/ignite/IgniteCache;II)I
 */
JNIEXPORT jint JNICALL Java_org_apache_ignite_examples_datagrid_CachePutGetComplexExample_zipcount
  (JNIEnv *, jobject, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
