/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_ignite_examples_datagrid_CachePutGetExample */

#ifndef _Included_org_apache_ignite_examples_datagrid_CachePutGetExample
#define _Included_org_apache_ignite_examples_datagrid_CachePutGetExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_ignite_examples_datagrid_CachePutGetExample
 * Method:    cppget
 * Signature: (Lorg/apache/ignite/IgniteCache;Ljava/lang/Integer;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_apache_ignite_examples_datagrid_CachePutGetExample_cppget
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
